repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.46.0
  hooks:
  - id: eslint
    additional_dependencies:
    - eslint@8.46.0
    - eslint-config-airbnb-base@15.0.0
    - eslint-plugin-import@2.28.0
